language: php

sudo: false

cache:
  directories:
  - vendor

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - ./vendor/bin/phpcs --colors --standard=PSR2 --extensions=php -n ./src
  - ./vendor/bin/phpcs --colors --standard=PSR2 --extensions=php -n ./tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

notifications:
  email: false
